language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# try running against postgres 9.3
#addons:
#  mysql: "5.5"

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  # show some versions and env information
  - php -r "echo INTL_ICU_VERSION . \"\n\";"
  - php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
  - mysql --version

script:
  - ./test.sh
